version: '0.0.1'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: growerlab
      POSTGRES_PASSWORD: growerlab
      POSTGRES_DB: growerlab
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data
  keydb:
    image: eqalpha/keydb
    ports:
      - "6379:6379"
    volumes:
      - ./data/keydb/data:/data
      - ./data/keydb/flash:/flash
  web:
    image: nginx
    volumes:
      - ./data/website:/usr/local/nginx/html
      - ./data/nginx/logs:/usr/local/var/log/nginx  # nginx的日志路径，后面的容器内路径应该与growerlab.conf中的符合
      - ./data/nginx/ssl:/etc/nginx/ssl             # nginx中的ssl路径
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=growerlab.com
      - NGINX_PORT=80
    command: /bin/bash -c "envsubst < ./data/nginx/growerlab.conf.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
  growerlab:
    build:
      dockerfile: Dockerfile   # find Dockerfile in root dir
      context: .
      args:
      labels:
        - "com.growerlab.description=growerlab services"
        - "com.growerlab.department=non"
        - "com.growerlab.by=moli"
      target: prod
