version: "3.7"
services:
  postgres:
    container_name: postgres
    image: postgres
    restart: "no"
    environment:
      POSTGRES_USER: growerlab
      POSTGRES_PASSWORD: growerlab
      POSTGRES_DB: growerlab_{{branchName}}
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data
    networks:
      - growerlab_net
  keydb:
    container_name: keydb
    image: eqalpha/keydb
    volumes:
      - ./data/keydb/data:/data
      - ./data/keydb/flash:/flash
    networks:
      - growerlab_net
  nginx:
    container_name: nginx
    image: nginx
    volumes:
      - ./data/nginx/conf:/etc/nginx/conf.d
      - ./data/website:/usr/local/nginx/html
      - ./data/nginx/logs:/usr/local/var/log/nginx # nginx的日志路径，后面的容器内路径应该与growerlab.conf中的符合
      - ./data/nginx/ssl:/etc/nginx/ssl # nginx中的ssl路径
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=growerlab.com
      - NGINX_PORT=80
    command: /bin/bash -c "exec nginx -g 'daemon off;'"
    networks:
      - growerlab_net
  growerlab:
    container_name: services_{{branchName}}
    depends_on: # 依赖启动顺序
      - postgres
      - keydb
      - nginx
    tty: true
    volumes:
      - ./data:/data
      - ./data/logs:/data/logs
    build:
      dockerfile: Dockerfile
      context: ./
      args:
        buildno: 1
      labels:
        - "com.growerlab.description=growerlab services"
        - "com.growerlab.department=dev"
        - "com.growerlab.by=moli"
    networks:
      - growerlab_net
networks:
  growerlab_net:
