default: &base
  debug: true
  website_url: http://localhost
  backend_port: 8081
  db_url: postgres://growerlab:growerlab@localhost:5432/growerlab?sslmode=false
  redis:
    host: 127.0.0.1
    port: 6379
    max_idle: 5
    max_active: 512
    idle_timeout: 120
    namespace: master

  # root dir for git repositores. the growerlab root dir is the default repositores dir.
  git_repo_dir: ../.repositories

  # go git grpc server
  go_git_grpc_server_addr: "127.0.0.1:9001"

  git_bin_path: "/usr/bin/git"

  mensa: &mensa
    user: git
    ssh_listen: 0.0.0.0:22
    http_listen: 0.0.0.0:8080
    https: true
    deadline: 3600
    idle_timeout: 30

local:
  <<: *base
  mensa:
    <<: *mensa
    ssh_listen: localhost:8022
    http_listen: localhost:8080
    https: false

dev:
  <<: *base

production:
  <<: *base
  debug: false
