default: &base
  debug: true
  website_url: http://localhost
  backend_port: 8081
  db_url: growerlab:growerlab@tcp(localhost:3306)/growerlab
  redis:
    host: 127.0.0.1
    port: 6379
    max_idle: 5
    max_active: 512
    idle_timeout: 120
    namespace: master

  # root dir for git repository
  git_repo_dir: /workspaces/growerlab/.repositories

  # go git grpc server
  go_git_grpc_server_addr: "127.0.0.1:9001"

  mensa:
    user: git
    ssh_listen: 0.0.0.0:8022
    http_listen: 0.0.0.0:8080
    deadline: 3600
    idle_timeout: 30
    git_path: /usr/bin/git

local:
  <<: *base
  mensa:
    ssh_listen: 0.0.0.0:8022

dev:
  <<: *base

production:
  debug: false
  <<: *base
