name: Services

on:
  workflow_dispatch:
    inputs:
      buildBranch:
        required: true
        default: "master"
        description: "编译的分支"
  # push:
  #   branches: [master]
  #   paths:
  #     - ".github/dev/services_deploy.sh"
  #     - ".github/workflows/dev_services.yml"
  #     - "dev.compose.yaml"

env:
  SERVER: ${{ secrets.GROWERLAB_SERVER }}
  SERVER_PORT: ${{ secrets.GROWERLAB_SERVER_PORT }}
  SERVER_USER: ${{ secrets.GROWERLAB_SERVER_USER }}
  SERVER_SSH_KEY: ${{ secrets.GROWERLAB_SERVER_SSH_KEY }}
  SERVER_POSTGRES_PASSWORD: ${{ secrets.GROWERLAB_POSTGRES_PASSWORD }}
  BUILD_BRANCH: ${{ github.event.inputs.buildBranch }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.19
        timeout-minutes: 5
        uses: actions/setup-go@v1
        with:
          go-version: "1.19"
        id: go

      - name: Check out code into the Go module directory
        timeout-minutes: 5
        uses: actions/checkout@v2

      - name: Build and deploy to dev server
        timeout-minutes: 5
        run: .github/dev/services_deploy.sh
