name: Services

on:
  push:
    branches: [master]
    paths:
      - ".github/events/frontend.event"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.14
        uses: actions/setup-go@v1
        with:
          go-version: 1.14
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: test1
        run: |
          git clone https://github.com/growerlab/backend.git --depth=1
          cd backend
          go get -v -t -d ./...
          go build -o backend -v main.go
          exit 1

      - name: test2
        run: |
          pwd

      - name: Get dependencies
        run: |
          go get -v -t -d ./...

      - name: Build
        run: go build -v .
